app:
  kafka:
    topic-api: topico-api-test
springdoc:
  pathsToMatch: /**,
  swagger-ui:
    tagsSorter: alpha
    disable-swagger-default-url: false
    path: /swagger
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

pom:
  version: @project.version@